### ISSUE TITLE
Code blocks are rendered with inconsistent font sizes on mobile

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-asciidoctor-backends#9] opened 2021-03-09 12:02 UTC
<details>
<summary>The font size used here matches the rest of the text</summary>

![IMG_6270](https://user-images.githubusercontent.com/914682/110467143-8c46ca80-80ce-11eb-9caf-f51807b4d2fb.PNG)
</details>

<details>
<summary>The font size used here is larger for some reason</summary>

![IMG_6269](https://user-images.githubusercontent.com/914682/110467147-8d77f780-80ce-11eb-8e6d-b246d28c82bd.PNG)
</details>

<details>
<summary>Expanding the imports results in a mixture of font sizes in the same block</summary>

![IMG_6271](https://user-images.githubusercontent.com/914682/110467386-db8cfb00-80ce-11eb-847a-655d2adb25a2.PNG)
</details>

**Comment by philwebb** [comment] 2021-03-09 18:46
Having a hard time replicating this, it looks to be specific to Apple devices (and I don't have any). I did find one font issue that I've pushed a fix for but I'm not convinced it'll solve this one.

**Comment by wilkinsona** [comment] 2021-03-09 19:50
It goes wrong in a different way on macOS Safari in responsive design mode.

<details>
<summary>There are two scroll bars, one for the imports and one for the main code</summary>

<img width="415" alt="Screenshot 2021-03-09 at 19 48 07" src="https://user-images.githubusercontent.com/914682/110528938-925d9b00-8110-11eb-8854-a509ff9acbfd.png">
</details>

I'll have a bit of a play with connecting web inspector to my phone and see if I can spot anything.

**Comment by wilkinsona** [comment] 2021-03-09 20:25
I thought it was something to do with the `<pre>` block not inheriting the `font-size` from `.doc pre`, but `<pre>` blocks with both the correct font size and the wrong font size don't show any styles inherited from `.doc pre`. I'm not sure how useful remote web inspector is as it doesn't seem to be showing the right data.

**Comment by wilkinsona** [comment] 2021-03-10 16:56
Unfortunately, the latest changes don't seem to have helped. I wondered if the problem was specific to Java code, i.e. blocks with code folding, but that's not the case.

<details>
<summary>Here are two Java code blocks, one with a large font size and one with the expected size</summary>

![IMG_94912EC2A993-1](https://user-images.githubusercontent.com/914682/110666756-854cb480-81c1-11eb-8c1e-e6f439a027be.jpeg)


</details>

**Comment by wilkinsona** [comment] 2021-03-10 20:00
Bingo. It doesn't seem to like the nested `<span>` elements. That's maybe fair enough as I think `<span>` is supposed to be an inline element and they're blocks here. I tried changing the outer `<span class="fold-block…">` elements to `<div>`s in web inspector and that seems to fix the problem.

**Comment by philwebb** [comment] 2021-03-11 00:23
I've replicated using the simulator from xcode. The issue is the `float:right` on the block which makes Safari think it can zoom the text. See https://stackoverflow.com/questions/20924039/wrong-font-size-when-using-float-right-in-css-on-mobile-safari

**Closed as completed** 2021-03-11 16:40 UTC
Labels: type: bug
