### ISSUE TITLE
Support custom banner logo and doc background

### ISSUE THREAD

**Issue by toedter** [spring-io/spring-asciidoctor-backends#34] opened 2021-04-25 19:27 UTC
While this asciidoctor backend is designed for Spring, I find it so great that I want to use it for non-Spring projects.
For that, it would be great if the banner-logo and the doc-background could be customized.

While the background is already available in light and dark flavors, this would also be great for custom logos.

**Comment by wilkinsona** [comment] 2021-04-26 08:18
Thanks for the suggestions. This is a duplicate of #24.

**Closed by wilkinsona** 2021-04-26 08:18 UTC
